cc_library(
    name = "service",
    srcs = [
        "Server.cpp",
        "Server.h",
        "Service.cpp",
        "Service.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//brain",
        "//brain/api/proto:api_grpc_proto",
    ],
)
