// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: common/proto/Statistics.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count              float64                      `protobuf:"fixed64,1,opt,name=count,proto3" json:"count,omitempty"`
	MinValue           float64                      `protobuf:"fixed64,2,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue           float64                      `protobuf:"fixed64,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Mean               float64                      `protobuf:"fixed64,4,opt,name=mean,proto3" json:"mean,omitempty"`
	StandardDeviation  float64                      `protobuf:"fixed64,5,opt,name=standard_deviation,json=standardDeviation,proto3" json:"standard_deviation,omitempty"`
	Cpk                float64                      `protobuf:"fixed64,6,opt,name=cpk,proto3" json:"cpk,omitempty"`
	TooSmallPercentage float64                      `protobuf:"fixed64,7,opt,name=too_small_percentage,json=tooSmallPercentage,proto3" json:"too_small_percentage,omitempty"`
	TooBigPercentage   float64                      `protobuf:"fixed64,8,opt,name=too_big_percentage,json=tooBigPercentage,proto3" json:"too_big_percentage,omitempty"`
	Defects            float64                      `protobuf:"fixed64,9,opt,name=defects,proto3" json:"defects,omitempty"`
	HistogramBegin     float64                      `protobuf:"fixed64,10,opt,name=histogram_begin,json=histogramBegin,proto3" json:"histogram_begin,omitempty"`
	HistogramEnd       float64                      `protobuf:"fixed64,11,opt,name=histogram_end,json=histogramEnd,proto3" json:"histogram_end,omitempty"`
	HistogramWidth     float64                      `protobuf:"fixed64,12,opt,name=histogram_width,json=histogramWidth,proto3" json:"histogram_width,omitempty"`
	Entries            []*Statistics_HistogramEntry `protobuf:"bytes,13,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_Statistics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_Statistics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_common_proto_Statistics_proto_rawDescGZIP(), []int{0}
}

func (x *Statistics) GetCount() float64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Statistics) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *Statistics) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Statistics) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Statistics) GetStandardDeviation() float64 {
	if x != nil {
		return x.StandardDeviation
	}
	return 0
}

func (x *Statistics) GetCpk() float64 {
	if x != nil {
		return x.Cpk
	}
	return 0
}

func (x *Statistics) GetTooSmallPercentage() float64 {
	if x != nil {
		return x.TooSmallPercentage
	}
	return 0
}

func (x *Statistics) GetTooBigPercentage() float64 {
	if x != nil {
		return x.TooBigPercentage
	}
	return 0
}

func (x *Statistics) GetDefects() float64 {
	if x != nil {
		return x.Defects
	}
	return 0
}

func (x *Statistics) GetHistogramBegin() float64 {
	if x != nil {
		return x.HistogramBegin
	}
	return 0
}

func (x *Statistics) GetHistogramEnd() float64 {
	if x != nil {
		return x.HistogramEnd
	}
	return 0
}

func (x *Statistics) GetHistogramWidth() float64 {
	if x != nil {
		return x.HistogramWidth
	}
	return 0
}

func (x *Statistics) GetEntries() []*Statistics_HistogramEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Statistics_HistogramEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Statistics_HistogramEntry) Reset() {
	*x = Statistics_HistogramEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_Statistics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistics_HistogramEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics_HistogramEntry) ProtoMessage() {}

func (x *Statistics_HistogramEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_Statistics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics_HistogramEntry.ProtoReflect.Descriptor instead.
func (*Statistics_HistogramEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_Statistics_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Statistics_HistogramEntry) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Statistics_HistogramEntry) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_common_proto_Statistics_proto protoreflect.FileDescriptor

var file_common_proto_Statistics_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x8d, 0x04, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x61,
	0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x61, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6d, 0x65, 0x61, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64,
	0x44, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x6b,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x63, 0x70, 0x6b, 0x12, 0x30, 0x0a, 0x14, 0x74,
	0x6f, 0x6f, 0x5f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x74, 0x6f, 0x6f, 0x53, 0x6d,
	0x61, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a,
	0x12, 0x74, 0x6f, 0x6f, 0x5f, 0x62, 0x69, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x74, 0x6f, 0x6f, 0x42, 0x69,
	0x67, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x64, 0x65,
	0x66, 0x65, 0x63, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x65, 0x6e, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x45, 0x6e, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x3b, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x2c, 0x0a, 0x0e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x42, 0x1f, 0x5a, 0x1d, 0x69, 0x73, 0x6f, 0x74, 0x72,
	0x6f, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_Statistics_proto_rawDescOnce sync.Once
	file_common_proto_Statistics_proto_rawDescData = file_common_proto_Statistics_proto_rawDesc
)

func file_common_proto_Statistics_proto_rawDescGZIP() []byte {
	file_common_proto_Statistics_proto_rawDescOnce.Do(func() {
		file_common_proto_Statistics_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_Statistics_proto_rawDescData)
	})
	return file_common_proto_Statistics_proto_rawDescData
}

var file_common_proto_Statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_Statistics_proto_goTypes = []interface{}{
	(*Statistics)(nil),                // 0: common.Statistics
	(*Statistics_HistogramEntry)(nil), // 1: common.Statistics.HistogramEntry
}
var file_common_proto_Statistics_proto_depIdxs = []int32{
	1, // 0: common.Statistics.entries:type_name -> common.Statistics.HistogramEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_Statistics_proto_init() }
func file_common_proto_Statistics_proto_init() {
	if File_common_proto_Statistics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_Statistics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_Statistics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistics_HistogramEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_Statistics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_Statistics_proto_goTypes,
		DependencyIndexes: file_common_proto_Statistics_proto_depIdxs,
		MessageInfos:      file_common_proto_Statistics_proto_msgTypes,
	}.Build()
	File_common_proto_Statistics_proto = out.File
	file_common_proto_Statistics_proto_rawDesc = nil
	file_common_proto_Statistics_proto_goTypes = nil
	file_common_proto_Statistics_proto_depIdxs = nil
}
